oculus_node:
  ros__parameters:
    ip: ""
    auto_discover: true
    tcp_port: 52100
    udp_port: 52102
    discover_timeout: 10.0
    connect_timeout: 15.0
    connect_retries: 3
    connect_retry_delay: 5.0
    read_error_retry_delay: 3.0
    no_ip_retry_delay: 10.0
    range_m: 10.0
    gain_percent: 30.0
    frame_id: "oculus"
    enhance_mode: "auto"
    publish_rate_hz: 0.0